// <auto-generated />
using Bulky.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bulky.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251024200520_AddProductTableAndSeedData")]
    partial class AddProductTableAndSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bulky.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "SciFi"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "History"
                        });
                });

            modelBuilder.Entity("Bulky.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "James Holden",
                            Description = "A motivational journey through success, failure, and the lessons of time.",
                            ISBN = "978-1000000001",
                            ListPrice = 899.0,
                            Price = 850.0,
                            Price100 = 750.0,
                            Price50 = 800.0,
                            Title = "Fortunes of Times"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Amelia Grant",
                            Description = "An emotional story exploring love, loss, and hope beneath dark skies.",
                            ISBN = "978-1000000002",
                            ListPrice = 799.0,
                            Price = 760.0,
                            Price100 = 680.0,
                            Price50 = 720.0,
                            Title = "Dark Skies Leaves and Wonders"
                        },
                        new
                        {
                            Id = 3,
                            Author = "William Carter",
                            Description = "A tale of resilience and courage as one stands strong against life's storms.",
                            ISBN = "978-1000000003",
                            ListPrice = 950.0,
                            Price = 900.0,
                            Price100 = 800.0,
                            Price50 = 850.0,
                            Title = "Rock in the Ocean"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Sophie Turner",
                            Description = "A lighthearted romantic comedy full of sweetness, laughter, and nostalgia.",
                            ISBN = "978-1000000004",
                            ListPrice = 699.0,
                            Price = 650.0,
                            Price100 = 550.0,
                            Price50 = 600.0,
                            Title = "Cotton Candy"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Noah Anderson",
                            Description = "A mysterious thriller about disappearing truths and chasing the impossible.",
                            ISBN = "978-1000000005",
                            ListPrice = 999.0,
                            Price = 950.0,
                            Price100 = 850.0,
                            Price50 = 900.0,
                            Title = "Vanish in the Sunset"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Luna Harper",
                            Description = "A futuristic sci-fi story about destiny, hope, and second chances.",
                            ISBN = "978-1000000006",
                            ListPrice = 899.0,
                            Price = 860.0,
                            Price100 = 780.0,
                            Price50 = 820.0,
                            Title = "Whispers of Tomorrow"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
